services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./create-intro/build/://usr/share/nginx/html

  flaskbackend:
    build:
      context: ./backend/
    ports:
      - 5000:5000
